# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82e36d79018c767021c8c144998894b43d1ae791338a1895a3e302e2c06ee45e0a2f70a87419f58277cee2c88312a05ca6e89b4fbb3a2f736b055c36d70b8e7b

test:
  secret_key_base: 470b7363918f0d524d261cfaa93b4f47224bee1a5f3c87563fe64c1556d150ee858d45d9ec9cd338e06c0a09bda01cd88fd374bf018518e34dd1e53b0418e51b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
